### ISSUE TITLE
How the weighs of the features are calculated

### ISSUE THREAD

**Issue by a1png** [Sage-Bionetworks/PDScores#6]
Hi,
I am now studying this project for a similar project but for another disease.
In https://github.com/Sage-Bionetworks/PDScores/blob/master/PDScores/PDScores/PDScores.m, the weights are written in the code.
I am wondering how these weights are calculated? Are they trained results of some machine learning algorithm? Is there any published paper about this?

Thanks

**Comment by Erin-Mounts** [comment]
Hi,

I ported this code to Objective-C from original Matlab code provided by [Max Little](http://www.maxlittle.net/home/index.php) which is included in this repository [here](https://github.com/Sage-Bionetworks/PDScores/tree/master/bridge_ufb%20(original)). 

I don't actually know how he derived those weights in the first place. He's published numerous papers relating to Parkinson's and monitoring it with mobile sensors (just search for Max Little on PubMed), but I couldn't tell you which if any relates to this particular piece of code he gave us for the original mPower project three years ago. 

His contact info is at the bottom of the page I linked to his name above, so you can ask him directly if you like. Sorry I'm not able to be more help.

**Comment by a1png** [comment]
I cannot find the weights in the original code by Max Little, so I thought these are the weights calculated by you.
But thank you for your help.

**Comment by Erin-Mounts** [comment]
Ah, right. I believe I got those weights from the Matlab workspace file bridge_features_example.mat, which I unfortunately can't open to double-check as I no longer have a current Matlab license.

**Comment by a1png** [comment]
ok, I'll test it myself
Thank you!
